# Auto-generated by lookup_zip_region_ids.py
# Paste this block into config.py to replace SEARCHES.

SEARCHES = [
]

# ── ZIPs not resolved — manual lookup needed ─────────────────────
# 1. Go to redfin.com, search the ZIP
# 2. DevTools → Network → filter 'location-autocomplete'
# 3. Copy region_id from the response JSON
#   28210  (28210 Charlotte SW)  status=http_403
#   28211  (28211 Charlotte SE)  status=http_403
#   28212  (28212 Charlotte E)  status=http_403
#   28213  (28213 Charlotte NE)  status=http_403
#   28214  (28214 Charlotte NW)  status=http_403
#   28215  (28215 Charlotte NE2)  status=http_403
#   28216  (28216 Charlotte N)  status=http_403
#   28217  (28217 Charlotte S)  status=http_403
#   28226  (28226 Charlotte S2)  status=http_403
#   28227  (28227 Mint Hill)  status=http_403
#   28269  (28269 Charlotte N2)  status=http_403
#   28270  (28270 Charlotte SE2)  status=http_403
#   28277  (28277 Ballantyne)  status=http_403
#   28278  (28278 Charlotte SW2)  status=http_403
#   28134  (28134 Pineville)  status=http_403
#   28104  (28104 Matthews)  status=http_403
#   28105  (28105 Matthews E)  status=http_403
#   28025  (28025 Concord)  status=http_403
#   28027  (28027 Concord NE)  status=http_403
#   28075  (28075 Harrisburg)  status=http_403
#   28078  (28078 Huntersville)  status=http_403
#   28031  (28031 Cornelius)  status=http_403
#   28036  (28036 Davidson)  status=http_403
#   28012  (28012 Belmont)  status=http_403
#   28052  (28052 Gastonia)  status=http_403
#   28054  (28054 Gastonia E)  status=http_403
#   28056  (28056 Gastonia N)  status=http_403
#   29708  (29708 Fort Mill Tega Cay SC)  status=http_403
#   29707  (29707 Indian Land SC)  status=http_403
#   29710  (29710 Lake Wylie SC)  status=http_403
#   29730  (29730 Rock Hill SC)  status=http_403
#   29732  (29732 Rock Hill N SC)  status=http_403
#   29720  (29720 Lancaster SC)  status=http_403
